//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tbernaulie.cpp
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#include "Tbernaulie.h"
#include <iostream>

using namespace std;

Tbernaulie::Tbernaulie(Tnewton* newton, Tpower* power) {
    this->newton = newton;
    this->power = power;
    this->P = 1;
    cout << "Tworzenie obiektu Tbernaulie\n";
}

Tbernaulie::~Tbernaulie() {
    delete this->newton;
    delete this->power;
    cout << "Niszczenie obiektu Tbernaulie\n";
}

float Tbernaulie::bernaurlie(float n, float k, float p) {
    if(n <= 0 || n < k || p > 1 || p < 0) {
        cout << "Podano nieodpowiednie wartosci\n";
        return 0;
    }

    float newtonsymbol = this->newton->newton((int)n, (int)k);

    float power1 = this->power->power(p, (int)k);
    float power2 = this->power->power(1.0f - p, (int)(n - k));

    this->P = newtonsymbol * power1 * power2;
    return this->P;
}

////////////////////////////////////////////////////////////

int main()
{
    Tbernaulie* ber = new Tbernaulie(new Tnewton(new Tfactorial()), new Tpower());

    cout << "\nObliczanie prawdopodobienstwa\n";
    cout << "Wynik: " << ber->bernaurlie(12, 3, 0.3)<<"\n\n";

    delete ber;

    return 0;
}
