//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tbernaulie.h
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#if !defined(_TBERNAULIE_H)
#define _TBERNAULIE_H

#include "Tnewton.h"
#include "Tpower.h"

class Tbernaulie {
public:
	Tbernaulie(Tnewton* newton, Tpower* power);
	~Tbernaulie();
    float bernaurlie(float n, float k, float p);
private:
	float P;
	Tnewton* newton;
	Tpower* power;
};

#endif  //_TBERNAULIE_H
