//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tbernaulie.cpp
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#include "Tbernaulie.h"

Tbernaulie::Tbernaulie(Tnewton* newton, Tpower* power) {

}

Tbernaulie::~Tbernaulie() {

}

void Tbernaulie::bernaurlie(int n, int k, float p) {

}

