//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tfactorial.cpp
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#include "Tfactorial.h"

Tfactorial::Tfactorial() {

}

float Tfactorial::factorial(int n) {
    if(n<=1) return 1;

    return factorial(n-1)*n;
}

