//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tfactorial.cpp
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#include "Tfactorial.h"

Tfactorial::Tfactorial() {

}

void Tfactorial::factorial(int n) {

}

