//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tfactorial.cpp
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#include "Tfactorial.h"
#include <iostream>

using namespace std;

Tfactorial::Tfactorial() {
    cout << "Tworzenie obiektu Tfactorial\n";
}

Tfactorial::~Tfactorial() {
    cout << "Niszczenie obiektu Tfactorial\n";
}

float Tfactorial::factorial(int n) {
    if (n <= 1) return 1;

    float result = 1.0f;
    for (int i = 2; i <= n; ++i) { // Obliczanie silni pętlą for
        result *= i;
    }
    return result;
}

