//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tfactorial.h
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#if !defined(_TFACTORIAL_H)
#define _TFACTORIAL_H


class Tfactorial {
public:
	Tfactorial();
    float factorial(int n);
};

#endif  //_TFACTORIAL_H
