//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tnewton.cpp
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#include "Tnewton.h"

Tnewton::Tnewton(Tfactorial* factorial) {

}

Tnewton::~Tnewton() {

}

void Tnewton::newton(int n, int k) {

}

