//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tnewton.h
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#if !defined(_TNEWTON_H)
#define _TNEWTON_H


class Tnewton {
public:
	Tnewton(Tfactorial* factorial);
	~Tnewton();
	void newton(int n, int k);
private:
	Tfactorial* factorial;
};

#endif  //_TNEWTON_H
