//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tnewton.cpp
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#include "Tnewton.h"

Tnewton::Tnewton(Tfactorial* factorial) {
    this->factorial = factorial;
}

Tnewton::~Tnewton() {
    delete this->factorial;
}

float Tnewton::newton(int n, int k) {
    float f1 = this->factorial->factorial(n);
    float f2 = this->factorial->factorial(k);
    return f1/f2;
}

