//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tpower.cpp
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#include "Tpower.h"
#include <iostream>

using namespace std;

Tpower::Tpower() {
    cout << "Tworzenie obiektu Tpower\n";
}

Tpower::~Tpower() {
    cout << "Niszczenie obiektu Tpower\n";
}

float Tpower::power(float x, int n) {
    if (n == 0) return 1;
    if (n == 1) return x;

    return x * power(x, n - 1);
}
