//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tpower.cpp
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#include "Tpower.h"

Tpower::Tpower() {

}

float Tpower::power(int x, int n) {
    int result = 1;
    for (int i = 0; i < n; ++i) {
        result*=x;
    }

    return result;
}

