//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tpower.h
//  @ Date : 21.04.2026
//  @ Author : 
//
//


#if !defined(_TPOWER_H)
#define _TPOWER_H


class Tpower {
public:
	Tpower();
	void power(int x, int n);
};

#endif  //_TPOWER_H
